/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.microsoft.playwright:playwright:1.26.0")
    implementation("io.cucumber:cucumber-java:6.10.4")
    implementation("commons-io:commons-io:2.11.0")
    implementation("com.aventstack:extentreports:5.0.9")
    implementation("org.projectlombok:lombok:1.18.24")
    testImplementation("junit:junit:4.13.2")
    testImplementation("io.cucumber:cucumber-junit:6.10.4")
    testImplementation("tech.grasshopper:extentreports-cucumber6-adapter:2.13.0")
}

group = "org.example"
version = "1.0-SNAPSHOT"
description = "GemfireUI"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
